# Dockerized Config Server Compose
# 
# If you want to up the compose without change anything, then you have to clone the configurations repository,
# and clone from: https://github.com/maoerd/configuration.git to local /var
# 
version: "3"
services:
  primary-config-server:
    image: mengluo668/config-server:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "/tmp/primary-config-server:/tmp"
      - "/var/configuration/config-server/primary/:/config-server/config"
  backup-config-server:
    image: mengluo668/config-server:0.0.1-SNAPSHOT
    restart: always
    environment:
      - DEFAULT_CONFIG_SERVER_PORT=8889
    ports:
      - 8889:8889
    volumes:
      - "/tmp/backup-config-server:/tmp"
      - "/var/configuration/config-server/backup/:/config-server/config"